backend:
  name: github
  repo: ictintegratedhub/ACE-ICT-INTEGRATED-HUB
  branch: main
  auth_type: implicit
  app_id: missing

media_folder: static/images/uploads
public_folder: /static/images/uploads

collections:
  - name: posts
    label: Blog Posts
    folder: content/posts
    create: true
    extension: md
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        widget: string
      - name: date
        label: Date
        widget: datetime
      - name: thumbnail
        label: Thumbnail Image
        widget: image
        required: false
      - name: body
        label: Body
        widget: markdown